### ISSUE TITLE
6. Array - Todo List 2

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/hchocobar-03-react-hello#40]
# Arrays

## Repaso a conceptos de JavaScript

![imagen](https://github.com/4GeeksAcademy/hchocobar-react-hello/assets/45291267/85e28c70-d280-4fef-892f-99a1e6c7c261)

## Todo List with React

![imagen](https://github.com/4GeeksAcademy/hchocobar-react-hello/assets/45291267/d6075e3d-4227-470a-9428-29a3482f7796)

**Comment by hchocobar** [comment]
# Styles css

```css

.hidden-icon > span {
    visibility: hidden;
}
/* Muestra el icono cuando el cursor pase por encima del li */
.hidden-icon:hover > span {
    visibility: visible;
}

```
