### ISSUE TITLE
4. Simple Counter Bonus - useEffect

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/hchocobar-03-react-hello#7]
# Check List

- [x] Time to Code: Project Simple Counter Bonus
  - [x] useState() Ejemplos
- [x] useEffect()
  - [ ] Definiciones
  - [ ] Ejemplo

## useEffect()

doc: https://es.react.dev/reference/react/useEffect

- [ ] Definción: Declara un efecto con useEffect en el nivel superior de tu componente
- [ ] Sintaxis: useEffect(configuración, dependencias?)
  - [ ] configuración: La función con la lógica de tu Efecto.
    - [ ] return (opcional) que devuelve una función de limpieza con código de limpieza
  - [ ] dependencias opcionales:
    - [ ] La lista de todos los valores reactivos referenciados dentro del código de configuración. 
    - [ ] Si el array de dependencias está vacío, su efecto se volverá a ejecutar después de cada renderizado del componente

## Time to Code: Simple Counter Bonus

> Spain-50 Day 17

- [x] Agregar estilos en `index.css`
- [x] Crear un componente básico y probarlo
- [x] Crear estado counter
- [x] Agregar el código HTML al return
  - [x] h1, 
  - [ ] h2 con `{}`
  - [x] div.big-counter
  - [ ] div*11
    - [ ] 1 div para el icono
    - [ ] 8 divs para los dígitos
    - [ ]  1 div para la coma
    - [x] 1 div para el grupo de botones
      - [ ] boostrap - button group - vetical align
      - [x] boton principal: text y class en expresiones `{}` (start, pause, continue)
      - [x] boton reset
 - [x] Crear las funciones handle
   - [ ] Crear otros estados: isRunning, status {title, icon, titleStyle}
   - [ ] handleButton
   - [ ] handleReset
- [ ] useEffect

**Comment by hchocobar** [comment]
![image](https://github.com/user-attachments/assets/996cae2e-dc82-4e9e-894f-2cf9969c1142)


```css

/* Simple Counter Bonus*/
.big-counter {
    text-align: center;
    background: black;
}

.big-counter div {
    display: inline-block;
    font-size: 60px;
    background: #161B22;
    border-radius: 5px;
    color: white;
    padding: 10px;
    margin: 3px;
}
```
