### ISSUE TITLE
3. useState() - StateExample - intro Traffic Light

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/hchocobar-03-react-hello#8]
# Check List

- [x] JavaScript: Desestructuración de array y objetos (en consola)
- [x] React: Hooks - useState()
- [x] Time to Code: useState() - componente: StateExample
- [ ] Proyecto: Traffic Light

> Atención: intercambiar clases. Primero Traffic Light (useState) , luego Simple Counter (useState + useEffect)

## Desestructuración

doc: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

> Spain 65 - Day19 - ver comment

## useState()

doc: https://es.react.dev/reference/react/useState

- [x] Variables Estado
- [x] Sintaxis: desestructura el estado y la función setter. El parámetro es el valor inicial del estado
- [x] Danger! Asignación a través de la función setter

## State Example

- [x] useState() - Syntax 
- [ ] Alert counter
- [ ] Button Group - Incrementar, Decrementar, Duplicar - state: number
- [x] Button Group - Mayúscula, Minúscula - state: paragraph
- [x] Button Group - Primary, Success, Warning, Danger - state: background

> Spain 65 - Day 19

## Proyecto: Traffic Light

```html
    <div className="container d-flex justify-content-around mt-5">
      <div className={`col-3 btn btn-success`}>
        Green
      </div>
      <div className={`col-3 btn btn-warning`}>
        Yellow
      </div>
      <div className={`col-3 btn btn-danger`}>
        Red
      </div>
    </div>
```

## Animación

```css

.glow-red {
  box-shadow: 0px 0px 9px 4px red;
  animation: glow 0.8s linear infinite alternate;
}
.glow-yellow {
  box-shadow: 0px 0px 9px 4px yellow;
  animation: glow 0.8s linear infinite alternate;
}
.glow-green {
  box-shadow: 0px 0px 9px 4px green;
  animation: glow 0.8s linear infinite alternate;
}

@keyframes glow {
  to {
      box-shadow: 0px 0px 30px 20px yellowgreen;
  }
}

```
